'use client';
import { useState } from 'react';
import { createWorker } from 'tesseract.js';
import { FileInput, Message, PrivacyNote, ResetButton, copyText, downloadText, fileToDataUrl } from './ToolShell';
export function OcrRunner({maxMB}:{maxMB:number}){
 const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState('');const [text,setText]=useState('');const [progress,setProgress]=useState(0);const [stage,setStage]=useState('Idle');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function choose(files:File[]){setFile(files[0]);setPreview(await fileToDataUrl(files[0]));setText('');setError('')}
 async function run(){if(!file)return;setBusy(true);setError('');setStage('Loading OCR engine');try{const worker=await createWorker('eng',1,{logger:m=>{setStage(m.status||'Processing');if(typeof m.progress==='number')setProgress(Math.round(m.progress*100))}});const result=await worker.recognize(file);setText(result.data.text);setStage('Completed');setProgress(100);await worker.terminate()}catch(e){setError(e instanceof Error?e.message:'OCR failed.');setStage('Failed')}finally{setBusy(false)}}
 function reset(){setFile(null);setPreview('');setText('');setProgress(0);setStage('Idle');setError('')}
 return <div className="card tool-workspace"><div className="panel tool-controls"><FileInput accept="image/jpeg,image/png,image/webp" maxMB={maxMB} onFiles={choose}/>{preview&&<img src={preview} alt="OCR source" style={{maxHeight:260,margin:'auto',borderRadius:12}}/>}<div className="action-row"><button className="btn btn-primary" disabled={!file||busy} onClick={run}>{busy?'Recognizing…':'Extract text'}</button><ResetButton onClick={reset}/></div>{busy&&<div className="status">{stage} · {progress}%<div style={{height:8,background:'var(--border)',borderRadius:999,marginTop:8}}><div style={{height:'100%',width:`${progress}%`,background:'var(--gradient)',borderRadius:999}}/></div></div>}{error&&<Message type="error">{error}</Message>}<PrivacyNote/></div><div className="panel"><h3>Extracted text</h3><textarea className="textarea" style={{minHeight:330}} value={text} onChange={e=>setText(e.target.value)} placeholder="Recognized text will appear here."/><div className="action-row" style={{marginTop:12}}><button className="btn btn-secondary" onClick={()=>copyText(text)}>Copy</button><button className="btn btn-secondary" onClick={()=>downloadText(text,'dotvec-ocr.txt')}>Download TXT</button></div><p className="help">Accuracy depends on image clarity, resolution, font and language.</p></div></div>
}
