'use client';
import { useMemo, useState } from 'react';
import { copyText, downloadText, Message, OutputCode, ResetButton } from './ToolShell';

function esc(s:string){return s.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
export function SeoRunner({slug}:{slug:string}){
 const [fields,setFields]=useState<Record<string,string>>({title:'Dotvec Tools',description:'Free private online tools that work in your browser.',url:'https://example.com/page',image:'https://example.com/image.jpg',site:'Dotvec Tools',source:'google',medium:'cpc',campaign:'summer'});
 const [rows,setRows]=useState<Array<Record<string,string>>>([{url:'https://example.com/',lang:'en',lastmod:new Date().toISOString().slice(0,10),priority:'1.0'}]);
 const set=(k:string,v:string)=>setFields(f=>({...f,[k]:v}));
 const output=useMemo(()=>generate(slug,fields,rows),[slug,fields,rows]);
 if(slug==='serp-preview')return <div className="card tool-workspace"><div className="panel tool-controls"><F label="Title" value={fields.title} set={v=>set('title',v)}/><F label="Description" value={fields.description} set={v=>set('description',v)} area/><F label="URL" value={fields.url} set={v=>set('url',v)}/><Message>{fields.title.length}/60 title characters · {fields.description.length}/160 description characters</Message></div><div className="panel"><h3>Desktop preview</h3><div className="card" style={{padding:20}}><div style={{fontSize:13,color:'var(--success)'}}>{fields.url}</div><div style={{fontSize:21,color:'#1a0dab',margin:'4px 0'}}>{fields.title.slice(0,60)}</div><p style={{margin:0,color:'var(--text-2)'}}>{fields.description.slice(0,160)}</p></div></div></div>;
 if(slug==='sitemap-generator'||slug==='hreflang-generator')return <RowsTool slug={slug} rows={rows} setRows={setRows} output={output}/>;
 return <div className="card tool-workspace"><div className="panel tool-controls"><Fields slug={slug} fields={fields} set={set}/><div className="action-row"><button className="btn btn-secondary" onClick={()=>copyText(output)}>Copy output</button><button className="btn btn-secondary" onClick={()=>downloadText(output,`dotvec-${slug}.${slug.includes('sitemap')?'xml':'txt'}`)}>Download</button><ResetButton onClick={()=>setFields({title:'',description:'',url:'',image:'',site:'',source:'',medium:'',campaign:''})}/></div></div><div className="panel"><h3>Generated output</h3><OutputCode value={output}/></div></div>
}
function F({label,value,set,area=false}:{label:string;value:string;set:(v:string)=>void;area?:boolean}){return <div className="field"><label className="label">{label}</label>{area?<textarea className="textarea" style={{minHeight:90}} value={value} onChange={e=>set(e.target.value)}/>:<input className="input" value={value} onChange={e=>set(e.target.value)}/>}</div>}
function Fields({slug,fields,set}:{slug:string;fields:Record<string,string>;set:(k:string,v:string)=>void}){const common=<><F label="Title" value={fields.title||''} set={v=>set('title',v)}/><F label="Description" value={fields.description||''} set={v=>set('description',v)} area/><F label="Page URL" value={fields.url||''} set={v=>set('url',v)}/></>;switch(slug){case'meta-tags-generator':return <>{common}<F label="Author" value={fields.author||''} set={v=>set('author',v)}/><F label="Robots" value={fields.robots||'index, follow'} set={v=>set('robots',v)}/></>;case'open-graph-generator':case'twitter-card-generator':return <>{common}<F label="Image URL" value={fields.image||''} set={v=>set('image',v)}/><F label="Site name / handle" value={fields.site||''} set={v=>set('site',v)}/></>;case'schema-generator':return <>{common}<div className="field"><label className="label">Schema type</label><select className="select" value={fields.type||'SoftwareApplication'} onChange={e=>set('type',e.target.value)}><option>SoftwareApplication</option><option>Article</option><option>Product</option><option>LocalBusiness</option><option>FAQPage</option><option>HowTo</option></select></div><F label="Additional name / price / address" value={fields.extra||''} set={v=>set('extra',v)}/></>;case'robots-generator':return <><F label="User-agent" value={fields.agent||'*'} set={v=>set('agent',v)}/><F label="Disallow paths, one per line" value={fields.disallow||'/admin\n/private'} set={v=>set('disallow',v)} area/><F label="Sitemap URL" value={fields.url||''} set={v=>set('url',v)}/></>;case'canonical-generator':return <F label="Canonical URL" value={fields.url||''} set={v=>set('url',v)}/>;case'utm-generator':return <><F label="Website URL" value={fields.url||''} set={v=>set('url',v)}/><F label="Source" value={fields.source||''} set={v=>set('source',v)}/><F label="Medium" value={fields.medium||''} set={v=>set('medium',v)}/><F label="Campaign" value={fields.campaign||''} set={v=>set('campaign',v)}/><F label="Term (optional)" value={fields.term||''} set={v=>set('term',v)}/><F label="Content (optional)" value={fields.content||''} set={v=>set('content',v)}/></>;default:return common}}
function generate(slug:string,f:Record<string,string>,rows:Array<Record<string,string>>){switch(slug){case'meta-tags-generator':return `<title>${esc(f.title||'')}</title>\n<meta name="description" content="${esc(f.description||'')}">\n<meta name="author" content="${esc(f.author||'')}">\n<meta name="robots" content="${esc(f.robots||'index, follow')}">\n<link rel="canonical" href="${esc(f.url||'')}">`;case'open-graph-generator':return `<meta property="og:title" content="${esc(f.title||'')}">\n<meta property="og:description" content="${esc(f.description||'')}">\n<meta property="og:url" content="${esc(f.url||'')}">\n<meta property="og:image" content="${esc(f.image||'')}">\n<meta property="og:site_name" content="${esc(f.site||'')}">`;case'twitter-card-generator':return `<meta name="twitter:card" content="summary_large_image">\n<meta name="twitter:title" content="${esc(f.title||'')}">\n<meta name="twitter:description" content="${esc(f.description||'')}">\n<meta name="twitter:image" content="${esc(f.image||'')}">\n<meta name="twitter:site" content="${esc(f.site||'')}">`;case'schema-generator':{const type=f.type||'SoftwareApplication';const obj:any={'@context':'https://schema.org','@type':type,name:f.title,description:f.description,url:f.url};if(type==='SoftwareApplication'){obj.applicationCategory='UtilitiesApplication';obj.operatingSystem='Web';obj.offers={'@type':'Offer',price:'0',priceCurrency:'USD'}}if(type==='Article')obj.headline=f.title;if(type==='Product')obj.offers={'@type':'Offer',price:f.extra||'0',priceCurrency:'USD'};if(type==='LocalBusiness')obj.address=f.extra;return `<script type="application/ld+json">\n${JSON.stringify(obj,null,2)}\n</script>`}case'robots-generator':return `User-agent: ${f.agent||'*'}\n${(f.disallow||'').split(/\r?\n/).filter(Boolean).map(x=>`Disallow: ${x}`).join('\n')}\nSitemap: ${f.url||''}`;case'sitemap-generator':return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${rows.map(r=>`  <url><loc>${esc(r.url||'')}</loc><lastmod>${r.lastmod||''}</lastmod><priority>${r.priority||'0.5'}</priority></url>`).join('\n')}\n</urlset>`;case'canonical-generator':return `<link rel="canonical" href="${esc(f.url||'')}">`;case'hreflang-generator':return rows.map(r=>`<link rel="alternate" hreflang="${esc(r.lang||'en')}" href="${esc(r.url||'')}">`).join('\n');case'utm-generator':{try{const u=new URL(f.url||'https://example.com');for(const k of ['source','medium','campaign','term','content'])if(f[k])u.searchParams.set(`utm_${k}`,f[k]);return u.toString()}catch{return 'Enter a valid website URL.'}}default:return ''}}
function RowsTool({slug,rows,setRows,output}:{slug:string;rows:Array<Record<string,string>>;setRows:(r:Array<Record<string,string>>)=>void;output:string}){function update(i:number,k:string,v:string){setRows(rows.map((r,n)=>n===i?{...r,[k]:v}:r))}return <div className="card" style={{padding:24}}><div className="grid">{rows.map((r,i)=><div key={i} className="grid grid-3"><input className="input" value={r.url||''} onChange={e=>update(i,'url',e.target.value)} placeholder="https://example.com/page"/><input className="input" value={slug==='hreflang-generator'?(r.lang||'en'):(r.lastmod||'')} onChange={e=>update(i,slug==='hreflang-generator'?'lang':'lastmod',e.target.value)} placeholder={slug==='hreflang-generator'?'en-US':'2026-07-02'}/><button className="btn btn-danger" onClick={()=>setRows(rows.filter((_,n)=>n!==i))}>Remove</button></div>)}</div><div className="action-row" style={{margin:'16px 0'}}><button className="btn btn-secondary" onClick={()=>setRows([...rows,{url:'',lang:'en',lastmod:new Date().toISOString().slice(0,10),priority:'0.5'}])}>Add row</button><button className="btn btn-secondary" onClick={()=>copyText(output)}>Copy output</button><button className="btn btn-primary" onClick={()=>downloadText(output,slug==='sitemap-generator'?'sitemap.xml':'hreflang.txt')}>Download</button></div><OutputCode value={output}/></div>}
